### PR TITLE
Update wincmd.c

### PR DESCRIPTION
**Pull request by kurokawachan**
Fixing issue

https://github.com/lxde/lxpanel/issues/77

### CODE REVIEW

**Comment by ib** [comment]
Please note that

- you could add the GDK_BUTTON_PRESS check to `if (event->button == 1)`.
- you still get [two](https://docs.gtk.org/gdk3/struct.EventButton.html) GDK_BUTTON_PRESS events.

In your commit, you should briefly explain what you changed and why. This will make it easier to understand later.

**Comment by kurokawachan** [comment]
Thanks,

 

>   you could add the GDK_BUTTON_PRESS check to if (event->button == 1).
 
Yes, it make sense

> you still get [two](https://docs.gtk.org/gdk3/struct.EventButton.html) GDK_BUTTON_PRESS events

Yes, and it is the right behavior. 
What we are trying to avoid is this function being trigger by `GDK_2BUTTON_PRESS` events. 

If we click the toggle too fast, an `GDK_2BUTTON_PRESS` would be triggered. 
If we click the toggle Not fast, no `GDK_2BUTTON_PRESS` would be triggered. 

I believe this toggle should only toggle on and off, double click does not make sense. 

I would draft another pull request.

**Comment by kurokawachan** [comment]
Hello @ib I just updated the GDK_BUTTON_PRESS check as you requested.

**Comment by ib** [comment]
I was thinking of something more straightforward and easier to understand.

You gave the description in your issue and pull request comments, but that should go in the commit message.

I have edited your patch. If you agree with it, I'll apply it.

**Comment by kurokawachan** [comment]
Hello, please do. Thanks

**Comment by ib** [comment]
Thank you very much for your contribution.

**Pull request merged**
